#!/bin/sh
#
# Card Reader
#
# Starts card_reader service.
#

DAEMON="card_reader"
PIDFILE="/var/run/$DAEMON.pid"

start() {
    printf 'Starting %s: ' "$DAEMON"
    start-stop-daemon \
        --start \
        --make-pidfile \
        --pidfile "$PIDFILE" \
        --exec "/usr/bin/$DAEMON" \
        --background \
        --quiet
    status=$?
    [ "$status" -eq 0 ] && echo "OK" || echo "FAIL"
    return "$status"
}
stop() {
    printf 'Stopping %s: ' "$DAEMON"
    start-stop-daemon \
        --stop \
        --quiet \
        --remove-pidfile \
        --pidfile "$PIDFILE"
    status=$?
    [ "$status" -eq 0 ] && echo "OK" || echo "FAIL"
    return "$status"
}
restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

